language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
- npm run migrate:test
- npm run seed:test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: mF2cwK72CNc/aLnxDV2CqLBwiYOOhKZ3uNkDMTTmy6MXaSL4d1j06uaUs4YRg7ffzFNHonJlCoesfpuu6Odkb6r9ffnBupddGnKVDy12+CgFlCaBzJioks2nfqWyFxmqKa8a0zQPKUm2L8bsc7y6gS3VkZa4CyOl2YkL/UoqR5MzRFSq9uhz7hFyGlBOYmdwzvXZOwwl+GvPIeRRXlp4JORbV26Q5WemFYJ5HM+D5iPRNuI2QbIfEzm1LQzYpRh1JZ/urMQXyf8GQJjLvDDxSOy4oyOnC1AJhzUgKOi2lhULRK7O8z21I5y3t/sl+jSmJdIF2eAZhSWpOnxJZhGiZ4ang/K+ypSos6HM7ZF5b9sDLhGzIY52B4rbUTpTKukcbcjle4T4cUtKqo/RjeUIk2gJrs635/8Gj3M88LACeNSQMmV92Bh8s6kx3jPQW96oe16XNNJF0tfxBdHWg0uJ0pdz1KccQIjL2HnZ8OqIqnBUSmproEMilz2vDk7tHVAuULCp2E/u+SnFIXkvcZlmIV3KQrt0uK/4sVE8hhaeV8tcdOmqn1aeInpEt8V5jdgrpfKAeJ0bI77csux8+5cQNac8FxYRLy1PpmcsCd1rel4b2HiV0olKMZ/npNzOhO0YJnqDoyUpu+3cHk9ES21NxeI8hYUto/xy3/d5qTurAIU=
  app: palette-picker-api
  skip_cleanup: true
